spring.application.name=Project-Toryment

spring.datasource.url=jdbc:postgresql://localhost:5432/toryment
spring.datasource.username=alex
spring.datasource.password=123
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api